#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# run_detvar_dfmaker.sh  (Step 1)
# ─────────────────────────
# Run your existing cafpyana run_df_maker.py + nueCC_mc.py config
# on each det-var file list, producing .df files identical in
# structure to your nominal production.
#
# This reuses YOUR EXACT pipeline — same make_nuecc_evtdf,
# same nue_selection.py cuts — just pointed at det-var CAFs.
#
# Usage:
#   # Run locally (one variation, for testing)
#   bash scripts/run_detvar_dfmaker.sh --var wiremodxtheta --nfile 1
#
#   # Run all variations locally
#   bash scripts/run_detvar_dfmaker.sh --var all
#
#   # Generate grid submission scripts
#   bash scripts/run_detvar_dfmaker.sh --var all --grid --njobs 20
#
# Prerequisites:
#   - File lists generated by make_detvar_filelists.sh
#   - cafpyana environment sourced
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

# ── Paths (adjust if needed) ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUECC_DIR="$(dirname "$SCRIPT_DIR")"
CAFPYANA_DIR="$(dirname "$(dirname "$NUECC_DIR")")"

FILELIST_DIR="/exp/sbnd/data/users/castalyf/nue_sel/production_files/detvar/filelists"
OUTPUT_BASE="/exp/sbnd/data/users/castalyf/nue_sel/production_files/detvar/detvar_dfs"

# Your run_df_maker.py location (from cafpyana)
RUN_DF_MAKER="${CAFPYANA_DIR}/run_df_maker.py"

# Your nueCC_mc.py config
DFMAKER_CONFIG="${NUECC_DIR}/makedf/nueCC_mc.py"

# ── Parse args ──
VAR="all"
NFILE=""
GRID=false
NJOBS=20
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --var)      VAR="$2"; shift 2 ;;
        --nfile)    NFILE="$2"; shift 2 ;;
        --grid)     GRID=true; shift ;;
        --njobs)    NJOBS="$2"; shift 2 ;;
        --dry-run)  DRY_RUN=true; shift ;;
        *)          echo "Unknown arg: $1"; exit 1 ;;
    esac
done

# ── Determine which variations to process ──
if [ "$VAR" = "all" ]; then
    VARS=()
    for fl in "${FILELIST_DIR}"/detvar_*.txt; do
        [ -f "$fl" ] || continue
        v=$(basename "$fl" .txt)
        v="${v#detvar_}"
        VARS+=("$v")
    done
    if [ ${#VARS[@]} -eq 0 ]; then
        echo "ERROR: No file lists found in $FILELIST_DIR"
        echo "Run make_detvar_filelists.sh first."
        exit 1
    fi
else
    VARS=("$VAR")
fi

echo "═══════════════════════════════════════════════════════════"
echo "  Det-var df maker"
echo "  Variations: ${VARS[*]}"
echo "  Output:     $OUTPUT_BASE"
echo "═══════════════════════════════════════════════════════════"

for var in "${VARS[@]}"; do
    filelist="${FILELIST_DIR}/detvar_${var}.txt"
    outdir="${OUTPUT_BASE}/${var}"
    mkdir -p "$outdir"

    if [ ! -f "$filelist" ]; then
        echo "WARNING: No file list for $var at $filelist — skipping"
        continue
    fi

    nfiles=$(wc -l < "$filelist")
    echo ""
    echo "── $var ($nfiles files) ──"
    echo "  File list: $filelist"
    echo "  Output:    $outdir"

    if $DRY_RUN; then
        echo "  [dry run] Would process $nfiles files"
        continue
    fi

    if $GRID; then
        # ── Generate grid submission ──
        GRID_DIR="${OUTPUT_BASE}/../grid_scripts"
        mkdir -p "$GRID_DIR"

        # Worker script
        WORKER="${GRID_DIR}/worker_${var}.sh"
        cat > "$WORKER" << WORKER_EOF
#!/bin/bash
# Grid worker for det-var: $var
# Auto-generated by run_detvar_dfmaker.sh

# Source your environment
source /exp/sbnd/app/users/castalyf/setup_cafpyana.sh
cd $NUECC_DIR

FILELIST="$filelist"
OUTDIR="$outdir"
NJOBS=$NJOBS
JOBID=\${PROCESS}

# Calculate file range for this job
NFILES=\$(wc -l < \$FILELIST)
FILES_PER_JOB=\$(( (NFILES + NJOBS - 1) / NJOBS ))
START=\$(( JOBID * FILES_PER_JOB + 1 ))
END=\$(( START + FILES_PER_JOB - 1 ))

# Extract this job's files into a temp list
TMPLIST=\$(mktemp /tmp/detvar_${var}_job\${JOBID}_XXXXXX.txt)
sed -n "\${START},\${END}p" \$FILELIST > \$TMPLIST

NTHIS=\$(wc -l < \$TMPLIST)
echo "Job \$JOBID: processing files \$START-\$END (\$NTHIS files)"

if [ \$NTHIS -eq 0 ]; then
    echo "No files for this job, exiting."
    rm -f \$TMPLIST
    exit 0
fi

# Run the df maker (same as nominal production!)
python $RUN_DF_MAKER \\
    -c $DFMAKER_CONFIG \\
    -l \$TMPLIST \\
    -o \${OUTDIR}/${var}_job\${JOBID}

rm -f \$TMPLIST
echo "Done."
WORKER_EOF
        chmod +x "$WORKER"

        # Submit script
        SUBMIT="${GRID_DIR}/submit_${var}.sh"
        cat > "$SUBMIT" << SUBMIT_EOF
#!/bin/bash
# Submit grid jobs for det-var: $var
# Usage: source $SUBMIT

jobsub_submit \\
    -G sbnd \\
    -N $NJOBS \\
    --memory=8GB \\
    --disk=10GB \\
    --expected-lifetime=4h \\
    --resource-provides=usage_model=OPPORTUNISTIC \\
    file://$WORKER

echo "Submitted $NJOBS jobs for $var"
echo "Output: $outdir"
SUBMIT_EOF
        chmod +x "$SUBMIT"

        echo "  Grid scripts:"
        echo "    Worker: $WORKER"
        echo "    Submit: $SUBMIT"

    else
        # ── Run locally ──
        NFILE_ARG=""
        if [ -n "$NFILE" ]; then
            NFILE_ARG="-nfile $NFILE"
        fi

        echo "  Running: python $RUN_DF_MAKER -c $DFMAKER_CONFIG -l $filelist -o ${outdir}/${var} $NFILE_ARG"

        python "$RUN_DF_MAKER" \
            -c "$DFMAKER_CONFIG" \
            -l "$filelist" \
            -o "${outdir}/${var}" \
            $NFILE_ARG
    fi
done

echo ""
echo "═══════════════════════════════════════════════════════════"
if $GRID; then
    echo "Grid scripts ready. Submit with:"
    for var in "${VARS[@]}"; do
        echo "  source ${OUTPUT_BASE}/../grid_scripts/submit_${var}.sh"
    done
else
    echo "Done. Output in: $OUTPUT_BASE"
fi
echo ""
echo "Next step: python scripts/merge_detvar_dfs.py"